version: '3'
services:
  redis-master:
    container_name: redis-master
    image: redis:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6380:6379"
    restart: always
  redis-slave-1:
    container_name: redis-slave-1
    image: redis:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6381:6379"
    restart: always
  redis-slave-2:
    container_name: redis-slave-2
    image: redis:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6382:6379"
    restart: always